INSERT INTO PRICE(VEHICLE_ID, CURRENCY, PRICE) VALUES(1, 'PLN', 2520);
INSERT INTO PRICE(VEHICLE_ID, CURRENCY, PRICE) VALUES(2, 'PLN', 1390);
INSERT INTO PRICE(VEHICLE_ID, CURRENCY, PRICE) VALUES(3, 'PLN', 1900);
INSERT INTO PRICE(VEHICLE_ID, CURRENCY, PRICE) VALUES(4, 'PLN', 2500.5);
INSERT INTO PRICE(VEHICLE_ID, CURRENCY, PRICE) VALUES(5, 'PLN', 2999.9);
INSERT INTO PRICE(VEHICLE_ID, CURRENCY, PRICE) VALUES(6, 'PLN', 5800);